<?php

//NOTES ABOUT SESSION:
// STORES DATA ON THE SERVER SIDE BUT STORES ITS SESSION ID ON THE CLIENT SIDE
// MORE SECURE BECAUSE DATA IS ON THE SERVER 
// ALWAYS NEED TO START SESSION ON EVERY LINKED PAGE 
// SESSIONS DONOT PERSIST ONCE THE BROWSER IS CLOSED


session_start(); //Generates SESSION ID

// $_SESSION["USERNAME"]="SAMAN";

echo $_SESSION["USERNAME"];
?>

<a href="about.php">About</a>
<a href="contact.php">Contact</a>


